# Generated by Django 5.1.8 on 2026-03-30 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
