# Generated by Django 6.0.3 on 2026-03-30 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='type',
            new_name='record_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='record_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the file contents', max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_url',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'record_date'], name='records_rec_user_id_941cfa_idx'),
        ),
    ]
