# Generated by Django 6.0.3 on 2026-03-30 15:00

import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetoken',
            name='expires_at',
            field=models.DateTimeField(default=sharing.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='sharetoken',
            name='token',
            field=models.CharField(default=sharing.models.generate_secure_token, max_length=64, unique=True),
        ),
    ]
